name: Java Build

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint edited and new files
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          VALIDATE_JAVA: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: mvn --batch-mode --update-snapshots test

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -DskipTests=true verify

      - name: Create directory for artifacts & copy artifacts
        run: mkdir staging && cp target/*.jar staging && mv staging/*.jar staging/app.jar

      - name: print staged files
        run: cd staging && ls -l

      - uses: actions/Upload-artifact@v3
        with:
          name: Package
          path: staging

  send:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: print staged files
        run: cd staging && ls -l

      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: staging/devOps-lab1-1.0-SNAPSHOT.jar