name: Java Build

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint edited and new files
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          VALIDATE_JAVA: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: mvn --batch-mode --update-snapshots test

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -DskipTests=true verify

      - name: Create directory for artifacts & copy artifacts
        run: mkdir staging && cp target/*.jar staging

      - uses: actions/Upload-artifact@v3
        with:
          name: Package
          path: staging